# This is a sample build configuration for Javascript (Node.js).
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: beneaththeink/node-xvfb:latest

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - export DISPLAY=:9.0
          - Xvfb -ac -screen scrn 1024x768x24 :9.0 &
          - npm install
          - npm rebuild
          - npm run test
